### PR TITLE
Support for all 24 EU languages

### PR DESCRIPTION
**Pull request by milovanderlinden**
Tested, working. Once this is merged, I will try and mobilize other Code Fellows to process their localization.

### CODE REVIEW

**Comment by milovanderlinden** [comment]
Please also not that the order of the Languages is alphabetic. I hope this pull request is acceptable.

**Comment by milovanderlinden** [comment]
Oops, accidentally closed!

**Comment by eraviart** [comment]
Thanks @milovanderlinden! Your work is very motivating for us.

**Comment by milovanderlinden** [comment]
thanks!

Don't forget to merge the retruco-api as well.

**Comment by eraviart** [comment]
Retruco-API has been merged and put in production Monday.

**Pull request merged**
